# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notes.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='notes.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bnotes.proto\"\x07\n\x05\x45mpty\" \n\x04Note\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04todo\x18\x02 \x01(\t\"!\n\tNotesList\x12\x14\n\x05notes\x18\x01 \x03(\x0b\x32\x05.Note\"\x16\n\x08NoteById\x12\n\n\x02id\x18\x01 \x01(\t2\x9b\x01\n\x0bNoteService\x12\x1e\n\x06GetAll\x12\x06.Empty\x1a\n.NotesList\"\x00\x12\x19\n\x03Get\x12\t.NoteById\x1a\x05.Note\"\x00\x12\x18\n\x06Insert\x12\x05.Note\x1a\x05.Note\"\x00\x12\x18\n\x06Update\x12\x05.Note\x1a\x05.Note\"\x00\x12\x1d\n\x06\x44\x65lete\x12\t.NoteById\x1a\x06.Empty\"\x00\x62\x06proto3'
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=22,
)


_NOTE = _descriptor.Descriptor(
  name='Note',
  full_name='Note',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Note.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='todo', full_name='Note.todo', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=56,
)


_NOTESLIST = _descriptor.Descriptor(
  name='NotesList',
  full_name='NotesList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='notes', full_name='NotesList.notes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=91,
)


_NOTEBYID = _descriptor.Descriptor(
  name='NoteById',
  full_name='NoteById',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='NoteById.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=115,
)

_NOTESLIST.fields_by_name['notes'].message_type = _NOTE
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Note'] = _NOTE
DESCRIPTOR.message_types_by_name['NotesList'] = _NOTESLIST
DESCRIPTOR.message_types_by_name['NoteById'] = _NOTEBYID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'notes_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

Note = _reflection.GeneratedProtocolMessageType('Note', (_message.Message,), {
  'DESCRIPTOR' : _NOTE,
  '__module__' : 'notes_pb2'
  # @@protoc_insertion_point(class_scope:Note)
  })
_sym_db.RegisterMessage(Note)

NotesList = _reflection.GeneratedProtocolMessageType('NotesList', (_message.Message,), {
  'DESCRIPTOR' : _NOTESLIST,
  '__module__' : 'notes_pb2'
  # @@protoc_insertion_point(class_scope:NotesList)
  })
_sym_db.RegisterMessage(NotesList)

NoteById = _reflection.GeneratedProtocolMessageType('NoteById', (_message.Message,), {
  'DESCRIPTOR' : _NOTEBYID,
  '__module__' : 'notes_pb2'
  # @@protoc_insertion_point(class_scope:NoteById)
  })
_sym_db.RegisterMessage(NoteById)



_NOTESERVICE = _descriptor.ServiceDescriptor(
  name='NoteService',
  full_name='NoteService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=118,
  serialized_end=273,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetAll',
    full_name='NoteService.GetAll',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_NOTESLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='NoteService.Get',
    index=1,
    containing_service=None,
    input_type=_NOTEBYID,
    output_type=_NOTE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Insert',
    full_name='NoteService.Insert',
    index=2,
    containing_service=None,
    input_type=_NOTE,
    output_type=_NOTE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Update',
    full_name='NoteService.Update',
    index=3,
    containing_service=None,
    input_type=_NOTE,
    output_type=_NOTE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Delete',
    full_name='NoteService.Delete',
    index=4,
    containing_service=None,
    input_type=_NOTEBYID,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_NOTESERVICE)

DESCRIPTOR.services_by_name['NoteService'] = _NOTESERVICE

# @@protoc_insertion_point(module_scope)
